export const certificates = [
  {
    "title": "React JS Tutorial",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (40).webp",
    "credential": "https://www.mygreatlearning.com/certificate/CUDKHDXO",
  },
  {
    "title": "Front End Web Development",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (37).webp",
    "credential": "https://www.mygreatlearning.com/certificate/DLGXITVV",
  },
  {
    "title": "Introduction to Web Development",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (30).webp",
    "credential": "https://www.mygreatlearning.com/certificate/HFZNDCDA",
  },
  {
    "title": "Introduction to Web Designing",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (18).webp",
    "credential": "https://www.mygreatlearning.com/certificate/AKNMZCQK",
  },
  {
    "title": "Front End Development - HTML",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (17).webp",
    "credential": "https://www.mygreatlearning.com/certificate/TJIPVCLS",
  },
  {
    "title": "Front End Development - CSS",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (16).webp",
    "credential": "https://www.mygreatlearning.com/certificate/EDYOIPNL",
  },
  {
    "title": "HTML Tutorial",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (29).webp",
    "credential": "https://www.mygreatlearning.com/certificate/SFYAQQCL",
  },
  {
    "title": "CSS Tutorial",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (13).webp",
    "credential": "https://www.mygreatlearning.com/certificate/HWAIAMAS",
  },
  {
    "title": "CSS Properties",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (12).webp",
    "credential": "https://www.mygreatlearning.com/certificate/MKITWBGQ",
  },
  {
    "title": "HTML Attributes and Tags",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (8).webp",
    "credential": "https://www.mygreatlearning.com/certificate/KJRHDFZU",
  },
  {
    "title": "JavaScript Projects",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (27).webp",
    "credential": "https://www.mygreatlearning.com/certificate/TXINCBYN",
  },
  {
    "title": "Introduction to JavaScript",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (25).webp",
    "credential": "https://www.mygreatlearning.com/certificate/NWXLPYFC",
  },
  {
    "title": "Introduction to Web API",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (33).webp",
    "credential": "https://www.mygreatlearning.com/certificate/CBKSUEHO",
  },
  {
    "title": "Ecommerce Website with HTML & CSS",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (28).webp",
    "credential": "https://www.mygreatlearning.com/certificate/BOOSNGCB",
  },
  {
    "title": "Create an IPL Theme Landing Page",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (34).webp",
    "credential": "https://www.mygreatlearning.com/certificate/CVUACUJH",
  },
  {
    "title": "Git Tutorial",
    "category": "Web Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (26).webp",
    "credential": "https://www.mygreatlearning.com/certificate/AAHQDOLI",
  },
  {
    "title": "Programming Essentials",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (32).webp",
    "credential": "https://www.mygreatlearning.com/certificate/YSBQNGNB",
  },
  {
    "title": "C for Beginners",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (21).webp",
    "credential": "https://www.mygreatlearning.com/certificate/ABYFHGTV",
  },
  {
    "title": "Algorithms in C",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (22).webp",
    "credential": "https://www.mygreatlearning.com/certificate/BGUCOZKK",
  },
  {
    "title": "C++ Tutorial",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (4).webp",
    "credential": "https://www.mygreatlearning.com/certificate/VVLSHOAI",
  },
  {
    "title": "Python Fundamentals",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (3).webp",
    "credential": "https://www.mygreatlearning.com/certificate/JDRAWLTK/",
  },
  {
    "title": "Python Applications & Use Cases",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (15).webp",
    "credential": "https://www.mygreatlearning.com/certificate/UOPULGDE",
  },
  {
    "title": "Prime Number Program",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (14).webp",
    "credential": "https://www.mygreatlearning.com/certificate/KMBJXKVZ",
  },
  {
    "title": "Palindrome Program",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (24).webp",
    "credential": "https://www.mygreatlearning.com/certificate/TFXTUPME",
  },
  {
    "title": "Introduction to Dart",
    "category": "Mobile Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (46).webp",
    "credential": "https://codesignal.com/learn/certificates/cmdgz0teh001sl204z4ylhnwx/course-paths/25",
  },
  {
    "title": "Dart Foundations",
    "category": "Mobile Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (42).webp",
    "credential": "https://codesignal.com/learn/certificates/cmdgz0teh001sl204z4ylhnwx/courses/118",
  },
  {
    "title": "Data Structures in Dart",
    "category": "Mobile Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (43).webp",
    "credential": "https://codesignal.com/learn/certificates/cmdgz0teh001sl204z4ylhnwx/courses/119",
  },
  {
    "title": "Functions in Dart",
    "category": "Mobile Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (45).webp",
    "credential": "https://codesignal.com/learn/certificates/cmdgz0teh001sl204z4ylhnwx/courses/121",
  },
  {
    "title": "Loops in Dart",
    "category": "Mobile Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (44).webp",
    "credential": "https://codesignal.com/learn/certificates/cmdgz0teh001sl204z4ylhnwx/courses/120",
  },
  {
    "title": "OOP in Dart",
    "category": "Mobile Development",
    "provider": "Great Learning",
    "image": "certificates/certificate (47).webp",
    "credential": "https://codesignal.com/learn/certificates/cmdgz0teh001sl204z4ylhnwx/courses/122",
  },
  {
    "title": "Generative AI with Diffusion Models",
    "category": "AI & Emerging Technologies",
    "provider": "aws",
    "image": "certificates/certificate (41).webp",
  },
  {
    "title": "ChatGPT for Beginners",
    "category": "AI & Emerging Technologies",
    "provider": "Great Learning",
    "image": "certificates/certificate (6).webp",
    "credential": "https://www.mygreatlearning.com/certificate/SHYSLRIH",
  },
  {
    "title": "Deepfakes Basics",
    "category": "AI & Emerging Technologies",
    "provider": "Great Learning",
    "image": "certificates/certificate (20).webp",
    "credential": "https://www.mygreatlearning.com/certificate/VKTPKQMD",
  },
  {
    "title": "LLM & NLP Participation Certificate",
    "category": "AI & Emerging Technologies",
    "provider": "MCAS College",
    "image": "certificates/certificate (2).webp",
  },
  {
    "title": "Ethical Hacking",
    "category": "Security & Networking",
    "provider": "Great Learning",
    "image": "certificates/certificate (7).webp",
    "credential": "https://www.mygreatlearning.com/certificate/MKPQZMYT",
  },
  {
    "title": "Information Security",
    "category": "Security & Networking",
    "provider": "Great Learning",
    "image": "certificates/certificate (5).webp",
    "credential": "https://www.mygreatlearning.com/certificate/IIUJHMPH",
  },
  {
    "title": "IoT",
    "category": "Security & Networking",
    "provider": "Great Learning",
    "image": "certificates/certificate (23).webp",
    "credential": "https://www.mygreatlearning.com/certificate/SABBDBJZ",
  },
  {
    "title": "UI/UX",
    "category": "Design",
    "provider": "Great Learning",
    "image": "certificates/certificate (35).webp",
    "credential": "https://www.mygreatlearning.com/certificate/ZDILLVQC",
  },
  {
    "title": "Design Thinking",
    "category": "Design",
    "provider": "Great Learning",
    "image": "certificates/certificate (31).webp",
    "credential": "https://www.mygreatlearning.com/certificate/FMWNGGZY",
  },
  {
    "title": "Resume Building",
    "category": "Others",
    "provider": "Great Learning",
    "image": "certificates/certificate (39).webp",
    "credential": "https://www.mygreatlearning.com/certificate/AKFRWNVE",
  },
  {
    "title": "Smart English for Professionals",
    "category": "Others",
    "provider": "Great Learning",
    "image": "certificates/certificate (38).webp",
    "credential": "https://www.mygreatlearning.com/certificate/PZETFKFC",
  },
  {
    "title": "Probability",
    "category": "Others",
    "provider": "Great Learning",
    "image": "certificates/certificate (11).webp",
    "credential": "https://www.mygreatlearning.com/certificate/IAXMQVHQ",
  },
  {
    "title": "Discrete Mathematics",
    "category": "Others",
    "provider": "Great Learning",
    "image": "certificates/certificate (19).webp",
    "credential": "https://www.mygreatlearning.com/certificate/MMYENFEA",
  },
  {
    "title": "Visual Studio Online",
    "category": "Others",
    "provider": "Great Learning",
    "image": "certificates/certificate (10).webp",
    "credential": "https://www.mygreatlearning.com/certificate/KMJYBDUF",
  },
  {
    "title": "Visual Studio Online",
    "category": "Programming",
    "provider": "Great Learning",
    "image": "certificates/certificate (36).webp",
    "credential": "https://www.mygreatlearning.com/certificate/QNJPSNAX",
  },
  {
    "title": "Mini CTF",
    "category": "Others",
    "provider": "JDT college",
    "image": "certificates/certificate (1).webp",
  }
]

// export const categories = [
//   "All",
//   "Programming",
//   "Web Development",
//   "AI & Emerging Technologies",
//   "Database",
//   "Mobile Development",
//   "Cloud & DevOps",
//   "Design",
//   "Cyber Security",
//   "Software Engineering",
//   "Tools"
// ];